StructuredBuffer<uint> srcBuffer0: register(t0);      // SRV
StructuredBuffer<uint> srcBuffer1: register(t1);      // SRV
RWStructuredBuffer<uint4> dstBuffer0: register(u0);    // UAV
RWStructuredBuffer<uint4> dstBuffer1: register(u1);    // UAV

cbuffer cbBuffer : register(b0) // CBV0
{
	float data0;
	float data1;
	float data2;
	float data3;
};

[numthreads(64, 1, 1)]
void BasicKernel(uint3 tid : SV_DispatchThreadID, uint3 groupID : SV_GroupID)
{
	dstBuffer0[tid.x] = uint4(srcBuffer0[tid.x], 7, WaveGetLaneIndex(), data3);
	dstBuffer1[tid.x] = uint4(srcBuffer1[tid.x], 9, WaveGetLaneIndex(), data1);
}
